### ISSUE TITLE
__ROADMAP__

### ISSUE THREAD

**Issue by cytopia** [cytopia/crawlpy#1]
# Roadmap
## v0.4
- [ ] First parse JS, then crawl (possibly via phantomJS)
## v0.3
- [ ] Make self-contained spider
## v0.2

[Release v0.2](https://github.com/cytopia/crawlpy/tree/v0.2)
- [X] ~~Be able to specify http status codes allowed for crawling (not just only `200`)~~
- [X] ~~overwrite internal DEPTH_LIMIT~~
- [x] ~~Ignore list of url patterns~~
## v0.1

[Release v0.1](https://github.com/cytopia/crawlpy/tree/v0.1)
- [X] ~~Make it work~~

**Comment by DjaPy** [comment]
Hi! I can help.
